//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int InventarioID { get; set; }
        public Nullable<int> ProductosID { get; set; }
        public int Numero_Existencia { get; set; }
        public decimal Precio_Venta { get; set; }
        public System.DateTime Fecha_Lote { get; set; }
        public System.DateTime Fecha_Vencimiento { get; set; }
        public Nullable<double> Descuento { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
